/** Short hello in the local language for a country code (ISO 3166-1 alpha-2). */
const GREETINGS: Record<string, string> = {
  NZ: 'Kia ora',
  AU: 'G’day',
  US: 'Hello',
  CA: 'Hello',
  GB: 'Hello',
  IE: 'Hello',
  FR: 'Bonjour',
  DE: 'Guten Tag',
  ES: 'Hola',
  IT: 'Ciao',
  PT: 'Olá',
  NL: 'Hallo',
  BE: 'Bonjour',
  CH: 'Grüezi',
  AT: 'Grüß Gott',
  GR: 'Γειά σου',
  TR: 'Merhaba',
  JP: 'こんにちは',
  KR: '안녕하세요',
  CN: '你好',
  HK: '你好',
  TW: '你好',
  TH: 'สวัสดี',
  VN: 'Xin chào',
  ID: 'Halo',
  MY: 'Selamat datang',
  SG: 'Ni hao',
  IN: 'Namaste',
  AE: 'مرحبا',
  SA: 'مرحبا',
  QA: 'مرحبا',
  EG: 'أهلا',
  MA: 'Salam',
  ZA: 'Sawubona',
  MX: 'Hola',
  BR: 'Olá',
  AR: 'Hola',
  CL: 'Hola',
  CO: 'Hola',
  PE: 'Hola',
  JM: 'Wah gwaan',
  BB: 'Hello',
  BS: 'Hello',
  RU: 'Привет',
  PL: 'Cześć',
  CZ: 'Ahoj',
  HU: 'Szia',
  SE: 'Hej',
  NO: 'Hei',
  DK: 'Hej',
  FI: 'Hei',
  IS: 'Halló',
  HR: 'Bok'
};

export function localGreetingForCountry(countryCode?: string): string | undefined {
  const code = (countryCode || '').trim().toUpperCase();
  if (!code) return undefined;
  return GREETINGS[code];
}
